before_install:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod u+x ./rebar3
install: "true"
language: erlang
sudo: false
otp_release:
  - 22.0
  - 21.0
script:
  - ./rebar3 as test get-deps
  - ./rebar3 as test proper -c
  - ./rebar3 as test ct -c
  - ./rebar3 as test cover
  - ./rebar3 as test coveralls send